### ISSUE TITLE
todo 앱을 만듭니다

### ISSUE THREAD

**Issue by lisia004** [lisia004/pre-test-app#1]
#무엇을 만드나요?
todo 앱을 만듭니다

#구현을 위해 해야 할 일은?

- [ ]  API계층부터 만듭니다. 컨트롤러 클래스부터 만듭니다.

- [ ]  DTO도 만듭니다.

- [ ]  서비스 계층인 서비스 클래스를 만들고

- [ ]  엔티티도 만듭니다.

- [ ]  이제 DTO와 엔티티를 매핑시킵니다.

- [ ]  그다음은 JPA를 이용해 데이터 베이스를 만들고 연결해줍니다. (JDBC 싫어요)

- [ ]  잘 작동하나요? 그렇다면 이제 유효성 검증을 해봅시다

- [ ]  이제 예외 처리도 하구요.

- [ ] API 문서화도 건드려보구요.

- [ ]  능력이 되면 슬라이스 테스트도 해봅시다

- [ ]  무섭지만 보안도 적용해볼까요? (백업은 잘해둡시다)

- [ ]  할만큼 했다면 이제 빌드, 실행, 배포를 합시다

- [ ]  마지막으로 모두 성공했다면 스스로에게 칭찬해줍니다.

# 예상 작업시간
2주안에 마무리할 수 있길 빕니다
